// $Id: language.h 1969 2012-05-31 01:48:19Z Colin $
// English: USA
// Navigation bar buttons and results

#define LANG_NB_LIST "List"
#define LANG_NB_MODIFY "Modify"
#define LANG_NB_CONFIRMMOD "Confirm Modify"
#define LANG_NB_NEW "New"
#define LANG_NB_DELETE "Delete"
#define LANG_NB_CONFIRMNEW "Create New Record"
#define LANG_NBB_CONFIRMNEW "<input class=lrevButton title='Double check!' type=submit name=gcCommand value=\"Create New Record\">"
#define LANG_NB_CONFIRMDEL "Confirm Delete"
#define LANG_NBB_CONFIRMDEL "<input class=lwarnButton title='No undo available!' type=submit name=gcCommand value=\"Confirm Delete\">"
#define LANG_NBB_CONFIRMMOD "<input class=lalertButton title='Double check!' type=submit name=gcCommand value=\"Confirm Modify\">"


#define LANG_NBR_FOUND " Found"
#define LANG_NBR_MODIFIED " Modified"
#define LANG_NBR_NEW " New"
#define LANG_NBR_NORECS " No records found"
#define LANG_NBRF_SHOWING " (Showing %lu of %d)"

#define LANG_NBR_RECEXISTS "<blink>Record already exists"
#define LANG_NBR_NEWRECADDED "New record %u added"
#define LANG_NBR_RECDELETED "Record Deleted"
#define LANG_NBR_RECNOTDELETED "Record Not Deleted"
#define LANG_NBR_RECNOTEXIST "<blink>Record does not exist"
#define LANG_NBR_MULTRECS "<blink>Multiple rows!"
#define LANG_NBR_EXTMOD "<blink>This record was just modified by another user!"
#define LANG_NBRF_REC_MODIFIED "record %s modified"

#define LANG_NBB_SKIPFIRST "<input class=first title='Skip to first record' type=submit name=gcFind value='<<' >"
#define LANG_NBB_SKIPBACK "<input class=back title='Go back one record' type=submit name=gcFind value='< ' >"
#define LANG_NBB_SKIPNEXT "<input class=next title='Advance to next record' type=submit name=gcFind value=' >' >"
#define LANG_NBB_SKIPLAST "<input class=last title='Skip to last record' type=submit name=gcFind value='>>' >\n"

#define LANG_NBB_NEWREV "<input class=revButton title='Create new record' type=submit name=gcCommand value=New>"
#define LANG_NBB_NEW "<input class=new title='Create new record' type=submit name=gcCommand value=New>"
#define LANG_NBB_DELETE "<input class=delete title='Delete current record' type=submit name=gcCommand value=Delete>"
#define LANG_NBB_MODIFY "<input class=modify title='Modify current record' type=submit name=gcCommand value=Modify>"

#define LANG_NBB_LIST "<input class=list title='Paginated listing of all records' type=submit name=gcFind value=List>"
#define LANG_NBB_SEARCH "<input class=refresh title='Find record with parameters set below' type=submit name=gcFind value=Search>"

#define LANG_PAGEMACHINE_HINT "No matching records found.<br>"
#define LANG_PAGEMACHINE_SHOWING "Page %d/%d (Records %d-%d of %d)\n"
#define LANG_PAGEMACHINE_SEARCH "<input type=submit name=gcFind value=Search >"
#define LANG_PAGEMACHINE_SEARCHBUTTON "Search"

//funcModuleLanguage()
#define LANG_FL_tPaciente_cLabel "cLabel"
#define LANG_FT_tPaciente_cLabel "Short label"
#define LANG_FL_tPaciente_dFechaNacimiento "dFechaNacimiento"
#define LANG_FT_tPaciente_dFechaNacimiento "Fecha de nacimiento del paciente"
#define LANG_FL_tPaciente_uCreatedDate "uCreatedDate"
#define LANG_FT_tPaciente_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tPaciente_cDireccion "cDireccion"
#define LANG_FT_tPaciente_cDireccion "Domicilio del paciente"
#define LANG_FL_tPaciente_cTelefonoCelular "cTelefonoCelular"
#define LANG_FT_tPaciente_cTelefonoCelular "Telefono celular del paciente"
#define LANG_FL_tPaciente_cNombre "cNombre"
#define LANG_FT_tPaciente_cNombre "Nombre del paciente"
#define LANG_FL_tPaciente_uPaciente "uPaciente"
#define LANG_FT_tPaciente_uPaciente "Primary key"
#define LANG_FL_tPaciente_uEdad "uEdad"
#define LANG_FT_tPaciente_uEdad "Edad del paciente"
#define LANG_FL_tPaciente_uCreatedBy "uCreatedBy"
#define LANG_FT_tPaciente_uCreatedBy "Record created by"
#define LANG_FL_tPaciente_uStatus "uStatus"
#define LANG_FT_tPaciente_uStatus "Estado del paciente"
#define LANG_FL_tPaciente_uModDate "uModDate"
#define LANG_FT_tPaciente_uModDate "Unix timestamp for last update"
#define LANG_FL_tPaciente_cTelefonoFijo "cTelefonoFijo"
#define LANG_FT_tPaciente_cTelefonoFijo "Telefono fijo del paciente"
#define LANG_FL_tPaciente_cApellido "cApellido"
#define LANG_FT_tPaciente_cApellido "Apellido del paciente"
#define LANG_FL_tPaciente_cTipoDocumento "cTipoDocumento"
#define LANG_FT_tPaciente_cTipoDocumento "Tipo del documento"
#define LANG_FL_tPaciente_uOwner "uOwner"
#define LANG_FT_tPaciente_uOwner "Record owner"
#define LANG_FL_tPaciente_uAfiliado "uAfiliado"
#define LANG_FT_tPaciente_uAfiliado "Numero de afiliado PAMI"
#define LANG_FL_tPaciente_uModBy "uModBy"
#define LANG_FT_tPaciente_uModBy "Record modifed by"
#define LANG_FL_tPaciente_cEmail "cEmail"
#define LANG_FT_tPaciente_cEmail "Correo electronico del paciente"
#define LANG_FL_tPaciente_cDocumento "cDocumento"
#define LANG_FT_tPaciente_cDocumento "Numero de documento del paciente"
#define LANG_FL_tConsulta_uConsulta "uConsulta"
#define LANG_FT_tConsulta_uConsulta "Primary key"
#define LANG_FL_tConsulta_uCreatedBy "uCreatedBy"
#define LANG_FT_tConsulta_uCreatedBy "Record created by"
#define LANG_FL_tConsulta_uModDate "uModDate"
#define LANG_FT_tConsulta_uModDate "Unix timestamp for last update"
#define LANG_FL_tConsulta_uPaciente "uPaciente"
#define LANG_FT_tConsulta_uPaciente "Paciente de la consulta"
#define LANG_FL_tConsulta_uOwner "uOwner"
#define LANG_FT_tConsulta_uOwner "Record owner"
#define LANG_FL_tConsulta_uLaboratorio "uLaboratorio"
#define LANG_FT_tConsulta_uLaboratorio "Ultimos laboratorios"
#define LANG_FL_tConsulta_uModBy "uModBy"
#define LANG_FT_tConsulta_uModBy "Record modifed by"
#define LANG_FL_tConsulta_cLabel "cLabel"
#define LANG_FT_tConsulta_cLabel "Short label"
#define LANG_FL_tConsulta_uCreatedDate "uCreatedDate"
#define LANG_FT_tConsulta_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tConsulta_uVitales "uVitales"
#define LANG_FT_tConsulta_uVitales "Ultimos signos vitales"
#define LANG_FL_tMotivo_uCreatedBy "uCreatedBy"
#define LANG_FT_tMotivo_uCreatedBy "Record created by"
#define LANG_FL_tMotivo_uModDate "uModDate"
#define LANG_FT_tMotivo_uModDate "Unix timestamp for last update"
#define LANG_FL_tMotivo_uOwner "uOwner"
#define LANG_FT_tMotivo_uOwner "Record owner"
#define LANG_FL_tMotivo_uModBy "uModBy"
#define LANG_FT_tMotivo_uModBy "Record modifed by"
#define LANG_FL_tMotivo_cLabel "cLabel"
#define LANG_FT_tMotivo_cLabel "Short label"
#define LANG_FL_tMotivo_uCreatedDate "uCreatedDate"
#define LANG_FT_tMotivo_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tMotivo_uMotivo "uMotivo"
#define LANG_FT_tMotivo_uMotivo "Primary key"
#define LANG_FL_tCentro_uOwner "uOwner"
#define LANG_FT_tCentro_uOwner "Record owner"
#define LANG_FL_tCentro_uModBy "uModBy"
#define LANG_FT_tCentro_uModBy "Record modifed by"
#define LANG_FL_tCentro_cLabel "cLabel"
#define LANG_FT_tCentro_cLabel "Short label"
#define LANG_FL_tCentro_uCreatedDate "uCreatedDate"
#define LANG_FT_tCentro_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tCentro_uCentro "uCentro"
#define LANG_FT_tCentro_uCentro "Primary key"
#define LANG_FL_tCentro_uCreatedBy "uCreatedBy"
#define LANG_FT_tCentro_uCreatedBy "Record created by"
#define LANG_FL_tCentro_uModDate "uModDate"
#define LANG_FT_tCentro_uModDate "Unix timestamp for last update"
#define LANG_FL_tAntecedente_uModBy "uModBy"
#define LANG_FT_tAntecedente_uModBy "Record modifed by"
#define LANG_FL_tAntecedente_cLabel "cLabel"
#define LANG_FT_tAntecedente_cLabel "Short label"
#define LANG_FL_tAntecedente_uCreatedDate "uCreatedDate"
#define LANG_FT_tAntecedente_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tAntecedente_uAntecedente "uAntecedente"
#define LANG_FT_tAntecedente_uAntecedente "Primary key"
#define LANG_FL_tAntecedente_uCreatedBy "uCreatedBy"
#define LANG_FT_tAntecedente_uCreatedBy "Record created by"
#define LANG_FL_tAntecedente_uModDate "uModDate"
#define LANG_FT_tAntecedente_uModDate "Unix timestamp for last update"
#define LANG_FL_tAntecedente_uOwner "uOwner"
#define LANG_FT_tAntecedente_uOwner "Record owner"
#define LANG_FL_tInternacion_cLabel "cLabel"
#define LANG_FT_tInternacion_cLabel "Short label"
#define LANG_FL_tInternacion_uCreatedDate "uCreatedDate"
#define LANG_FT_tInternacion_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tInternacion_uInternacion "uInternacion"
#define LANG_FT_tInternacion_uInternacion "Primary key"
#define LANG_FL_tInternacion_uCreatedBy "uCreatedBy"
#define LANG_FT_tInternacion_uCreatedBy "Record created by"
#define LANG_FL_tInternacion_uModDate "uModDate"
#define LANG_FT_tInternacion_uModDate "Unix timestamp for last update"
#define LANG_FL_tInternacion_uOwner "uOwner"
#define LANG_FT_tInternacion_uOwner "Record owner"
#define LANG_FL_tInternacion_uModBy "uModBy"
#define LANG_FT_tInternacion_uModBy "Record modifed by"
#define LANG_FL_tMedico_uMedico "uMedico"
#define LANG_FT_tMedico_uMedico "Primary key"
#define LANG_FL_tMedico_uCreatedBy "uCreatedBy"
#define LANG_FT_tMedico_uCreatedBy "Record created by"
#define LANG_FL_tMedico_uModDate "uModDate"
#define LANG_FT_tMedico_uModDate "Unix timestamp for last update"
#define LANG_FL_tMedico_uOwner "uOwner"
#define LANG_FT_tMedico_uOwner "Record owner"
#define LANG_FL_tMedico_uModBy "uModBy"
#define LANG_FT_tMedico_uModBy "Record modifed by"
#define LANG_FL_tMedico_cLabel "cLabel"
#define LANG_FT_tMedico_cLabel "Short label"
#define LANG_FL_tMedico_uCreatedDate "uCreatedDate"
#define LANG_FT_tMedico_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tMedicacion_uOwner "uOwner"
#define LANG_FT_tMedicacion_uOwner "Record owner"
#define LANG_FL_tMedicacion_uModBy "uModBy"
#define LANG_FT_tMedicacion_uModBy "Record modifed by"
#define LANG_FL_tMedicacion_cLabel "cLabel"
#define LANG_FT_tMedicacion_cLabel "Short label"
#define LANG_FL_tMedicacion_uCreatedDate "uCreatedDate"
#define LANG_FT_tMedicacion_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tMedicacion_uMedicacion "uMedicacion"
#define LANG_FT_tMedicacion_uMedicacion "Primary key"
#define LANG_FL_tMedicacion_uCreatedBy "uCreatedBy"
#define LANG_FT_tMedicacion_uCreatedBy "Record created by"
#define LANG_FL_tMedicacion_uModDate "uModDate"
#define LANG_FT_tMedicacion_uModDate "Unix timestamp for last update"
#define LANG_FL_tInmunizacion_uInmunizacion "uInmunizacion"
#define LANG_FT_tInmunizacion_uInmunizacion "Primary key"
#define LANG_FL_tInmunizacion_uCreatedBy "uCreatedBy"
#define LANG_FT_tInmunizacion_uCreatedBy "Record created by"
#define LANG_FL_tInmunizacion_uModDate "uModDate"
#define LANG_FT_tInmunizacion_uModDate "Unix timestamp for last update"
#define LANG_FL_tInmunizacion_uOwner "uOwner"
#define LANG_FT_tInmunizacion_uOwner "Record owner"
#define LANG_FL_tInmunizacion_uModBy "uModBy"
#define LANG_FT_tInmunizacion_uModBy "Record modifed by"
#define LANG_FL_tInmunizacion_uFecha "uFecha"
#define LANG_FT_tInmunizacion_uFecha "Fecha de colocación "
#define LANG_FL_tInmunizacion_cLabel "cLabel"
#define LANG_FT_tInmunizacion_cLabel "Short label"
#define LANG_FL_tInmunizacion_uCreatedDate "uCreatedDate"
#define LANG_FT_tInmunizacion_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tTipoConsulta_uTipoConsulta "uTipoConsulta"
#define LANG_FT_tTipoConsulta_uTipoConsulta "Primary key"
#define LANG_FL_tTipoConsulta_uCreatedBy "uCreatedBy"
#define LANG_FT_tTipoConsulta_uCreatedBy "Record created by"
#define LANG_FL_tTipoConsulta_uModDate "uModDate"
#define LANG_FT_tTipoConsulta_uModDate "Unix timestamp for last update"
#define LANG_FL_tTipoConsulta_uOwner "uOwner"
#define LANG_FT_tTipoConsulta_uOwner "Record owner"
#define LANG_FL_tTipoConsulta_uModBy "uModBy"
#define LANG_FT_tTipoConsulta_uModBy "Record modifed by"
#define LANG_FL_tTipoConsulta_cLabel "cLabel"
#define LANG_FT_tTipoConsulta_cLabel "Short label"
#define LANG_FL_tTipoConsulta_uCreatedDate "uCreatedDate"
#define LANG_FT_tTipoConsulta_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tLaboratorio_uOrina "uOrina"
#define LANG_FT_tLaboratorio_uOrina "Tabla de Orina"
#define LANG_FL_tLaboratorio_uCreatedDate "uCreatedDate"
#define LANG_FT_tLaboratorio_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tLaboratorio_cLabel "cLabel"
#define LANG_FT_tLaboratorio_cLabel "Short label"
#define LANG_FL_tLaboratorio_cOtro "cOtro"
#define LANG_FT_tLaboratorio_cOtro "Notas"
#define LANG_FL_tLaboratorio_uVirologia "uVirologia"
#define LANG_FT_tLaboratorio_uVirologia "Tabla de cargas virales"
#define LANG_FL_tLaboratorio_uSerologia "uSerologia"
#define LANG_FT_tLaboratorio_uSerologia "Tabla de Serologia"
#define LANG_FL_tLaboratorio_uModBy "uModBy"
#define LANG_FT_tLaboratorio_uModBy "Record modifed by"
#define LANG_FL_tLaboratorio_uOwner "uOwner"
#define LANG_FT_tLaboratorio_uOwner "Record owner"
#define LANG_FL_tLaboratorio_uSangre "uSangre"
#define LANG_FT_tLaboratorio_uSangre "Tabla de Sangre"
#define LANG_FL_tLaboratorio_cLaboratorio "cLaboratorio"
#define LANG_FT_tLaboratorio_cLaboratorio "Nombre del Laboratorio"
#define LANG_FL_tLaboratorio_uModDate "uModDate"
#define LANG_FT_tLaboratorio_uModDate "Unix timestamp for last update"
#define LANG_FL_tLaboratorio_uMicrobiologia "uMicrobiologia"
#define LANG_FT_tLaboratorio_uMicrobiologia "Tabla de Microbiologia"
#define LANG_FL_tLaboratorio_uCreatedBy "uCreatedBy"
#define LANG_FT_tLaboratorio_uCreatedBy "Record created by"
#define LANG_FL_tLaboratorio_uLaboratorio "uLaboratorio"
#define LANG_FT_tLaboratorio_uLaboratorio "Primary key"
#define LANG_FL_tLaboratorio_uPaciente "uPaciente"
#define LANG_FT_tLaboratorio_uPaciente "Numero de paciente"
#define LANG_FL_tSangre_uCD8 "uCD8"
#define LANG_FT_tSangre_uCD8 "Recuento de linfocitos T CD8+ n/uL"
#define LANG_FL_tSangre_uCreatedBy "uCreatedBy"
#define LANG_FT_tSangre_uCreatedBy "Record created by"
#define LANG_FL_tSangre_uCloro "uCloro"
#define LANG_FT_tSangre_uCloro "Cloro en Sangre mEq/l"
#define LANG_FL_tSangre_uPotasio "uPotasio"
#define LANG_FT_tSangre_uPotasio "Potasio en Sangre mEq/l"
#define LANG_FL_tSangre_uHematocrito "uHematocrito"
#define LANG_FT_tSangre_uHematocrito "Hematocrito %"
#define LANG_FL_tSangre_uFAL "uFAL"
#define LANG_FT_tSangre_uFAL "Fosftasa Alcalina U/L"
#define LANG_FL_tSangre_uSangre "uSangre"
#define LANG_FT_tSangre_uSangre "Primary key"
#define LANG_FL_tSangre_uBilD "uBilD"
#define LANG_FT_tSangre_uBilD "Bilirubina Directa mg/L"
#define LANG_FL_tSangre_uBasofilos "uBasofilos"
#define LANG_FT_tSangre_uBasofilos "Porentaje de Basofios %"
#define LANG_FL_tSangre_uTGP "uTGP"
#define LANG_FT_tSangre_uTGP "Transaminasa Glutamico Piruvica UI/L"
#define LANG_FL_tSangre_uMonocitos "uMonocitos"
#define LANG_FT_tSangre_uMonocitos "Porcentaje de Monocitos %"
#define LANG_FL_tSangre_uPCR "uPCR"
#define LANG_FT_tSangre_uPCR "Protiena C Reactiva"
#define LANG_FL_tSangre_cLaboratorio "cLaboratorio"
#define LANG_FT_tSangre_cLaboratorio "Nombre del Laboratorio"
#define LANG_FL_tSangre_uT4 "uT4"
#define LANG_FT_tSangre_uT4 "Tiroxina ug/dL"
#define LANG_FL_tSangre_uPlaquetas "uPlaquetas"
#define LANG_FT_tSangre_uPlaquetas "Plaquetas K/ul"
#define LANG_FL_tSangre_uCreatedDate "uCreatedDate"
#define LANG_FT_tSangre_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tSangre_uHb "uHb"
#define LANG_FT_tSangre_uHb "Hemoglobina gr/dl"
#define LANG_FL_tSangre_uAmilasa "uAmilasa"
#define LANG_FT_tSangre_uAmilasa " Amilasa en Sangre U/L"
#define LANG_FL_tSangre_cLabel "cLabel"
#define LANG_FT_tSangre_cLabel "Short label"
#define LANG_FL_tSangre_uCPK "uCPK"
#define LANG_FT_tSangre_uCPK "Creatin Fosfo Quinasa mg/dl"
#define LANG_FL_tSangre_uNeutrofilos "uNeutrofilos"
#define LANG_FT_tSangre_uNeutrofilos "Porcentaje de Neutrofilos Segmentados %"
#define LANG_FL_tSangre_uT3 "uT3"
#define LANG_FT_tSangre_uT3 "Triyodotironina ug/dL"
#define LANG_FL_tSangre_uGGT "uGGT"
#define LANG_FT_tSangre_uGGT "Gamma Glutamil Transpeptidasa UI/L"
#define LANG_FL_tSangre_uLinfocitos "uLinfocitos"
#define LANG_FT_tSangre_uLinfocitos "Porcentaje de Linfocitos %"
#define LANG_FL_tSangre_uVSG "uVSG"
#define LANG_FT_tSangre_uVSG "Velocidad de Eritrosedimentacion"
#define LANG_FL_tSangre_cOtro "cOtro"
#define LANG_FT_tSangre_cOtro "Notas"
#define LANG_FL_tSangre_uTSH "uTSH"
#define LANG_FT_tSangre_uTSH "Hormona Tirotropina uUI/mL"
#define LANG_FL_tSangre_uCreatinina "uCreatinina"
#define LANG_FT_tSangre_uCreatinina "Creatinina mg/dl"
#define LANG_FL_tSangre_uModBy "uModBy"
#define LANG_FT_tSangre_uModBy "Record modifed by"
#define LANG_FL_tSangre_uUrea "uUrea"
#define LANG_FT_tSangre_uUrea "Urea en Sangre mg/dl"
#define LANG_FL_tSangre_uCD4 "uCD4"
#define LANG_FT_tSangre_uCD4 "Recuento de linfocitos T CD4+ n/uL"
#define LANG_FL_tSangre_uOwner "uOwner"
#define LANG_FT_tSangre_uOwner "Record owner"
#define LANG_FL_tSangre_uSodio "uSodio"
#define LANG_FT_tSangre_uSodio "Sodio en Sangre mEq/l"
#define LANG_FL_tSangre_uLeucocitos "uLeucocitos"
#define LANG_FT_tSangre_uLeucocitos "Leucocitos K/ul"
#define LANG_FL_tSangre_uAlbumina "uAlbumina"
#define LANG_FT_tSangre_uAlbumina "Albumina en Sangre g/dL"
#define LANG_FL_tSangre_uBilT "uBilT"
#define LANG_FT_tSangre_uBilT "BilirubinaTotal mg/dl"
#define LANG_FL_tSangre_uEosinofilos "uEosinofilos"
#define LANG_FT_tSangre_uEosinofilos "Pordentaje de Eosinofios %"
#define LANG_FL_tSangre_uTGO "uTGO"
#define LANG_FT_tSangre_uTGO "Transaminasa Glutamico Oxalacetica UI/L"
#define LANG_FL_tSangre_uGlobulosRojos "uGlobulosRojos"
#define LANG_FT_tSangre_uGlobulosRojos "Globulos Rojos M/ul"
#define LANG_FL_tSangre_uGlucemia "uGlucemia"
#define LANG_FT_tSangre_uGlucemia "Glucemia mg/dl"
#define LANG_FL_tSangre_uModDate "uModDate"
#define LANG_FT_tSangre_uModDate "Unix timestamp for last update"
#define LANG_FL_tSangre_uLDH "uLDH"
#define LANG_FT_tSangre_uLDH "Lactato deshidrogenasa U/Ll"
#define LANG_FL_tSerologia_uHBVsAg "uHBVsAg"
#define LANG_FT_tSerologia_uHBVsAg " Hepatitis B antigeno de superficie positivo negativo"
#define LANG_FL_tSerologia_uHVC "uHVC"
#define LANG_FT_tSerologia_uHVC " Hepatitis C anticuerpo positivo negativo"
#define LANG_FL_tSerologia_uCVHVC "uCVHVC"
#define LANG_FT_tSerologia_uCVHVC " Carga viral Hepatitis C copias/mL"
#define LANG_FL_tSerologia_uModDate "uModDate"
#define LANG_FT_tSerologia_uModDate "Unix timestamp for last update"
#define LANG_FL_tSerologia_uCreatedBy "uCreatedBy"
#define LANG_FT_tSerologia_uCreatedBy "Record created by"
#define LANG_FL_tSerologia_uToxoIgM "uToxoIgM"
#define LANG_FT_tSerologia_uToxoIgM " Toxoplasmosis anticuerpo IgM positivo negativo"
#define LANG_FL_tSerologia_cLabel "cLabel"
#define LANG_FT_tSerologia_cLabel "Short label"
#define LANG_FL_tSerologia_uHVAIgG "uHVAIgG"
#define LANG_FT_tSerologia_uHVAIgG " Hepatitis A anticuerpo IgG positivo negativo"
#define LANG_FL_tSerologia_uHVBanticoreIgG "uHVBanticoreIgG"
#define LANG_FT_tSerologia_uHVBanticoreIgG " Hepatitis B antigeno del core anticuerpo IgG positivo negativo"
#define LANG_FL_tSerologia_uCVHVB "uCVHVB"
#define LANG_FT_tSerologia_uCVHVB " Carga viral Hepatits B copias/mL"
#define LANG_FL_tSerologia_cNotas "cNotas"
#define LANG_FT_tSerologia_cNotas "Notas de Serologia"
#define LANG_FL_tSerologia_uHIV "uHIV"
#define LANG_FT_tSerologia_uHIV " Virus de la inmunodeficiencia humana positivo negativo"
#define LANG_FL_tSerologia_uCreatedDate "uCreatedDate"
#define LANG_FT_tSerologia_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tSerologia_uToxoIgG "uToxoIgG"
#define LANG_FT_tSerologia_uToxoIgG " Toxoplasmosis anticuerpo IgG positivo negativo"
#define LANG_FL_tSerologia_uSerologia "uSerologia"
#define LANG_FT_tSerologia_uSerologia "Primary key"
#define LANG_FL_tSerologia_uCMVIgM "uCMVIgM"
#define LANG_FT_tSerologia_uCMVIgM " Citomegalovirus anticuerpo IgM positivo negativo"
#define LANG_FL_tSerologia_uHVBanticoreIgM "uHVBanticoreIgM"
#define LANG_FT_tSerologia_uHVBanticoreIgM " Hepatitis B antigeno del core anticuerpo IgM positivo negativo"
#define LANG_FL_tSerologia_uHVAIgM "uHVAIgM"
#define LANG_FT_tSerologia_uHVAIgM " Hepatitis A anticuerpo IgM positivo negativo"
#define LANG_FL_tSerologia_uCVHIV "uCVHIV"
#define LANG_FT_tSerologia_uCVHIV " Carga Viral HIV copias/mL"
#define LANG_FL_tSerologia_uModBy "uModBy"
#define LANG_FT_tSerologia_uModBy "Record modifed by"
#define LANG_FL_tSerologia_uChagas "uChagas"
#define LANG_FT_tSerologia_uChagas " Enfermedad de Chagas positivo negativo"
#define LANG_FL_tSerologia_uOwner "uOwner"
#define LANG_FT_tSerologia_uOwner "Record owner"
#define LANG_FL_tMicrobiologia_uCreatedBy "uCreatedBy"
#define LANG_FT_tMicrobiologia_uCreatedBy "Record created by"
#define LANG_FL_tMicrobiologia_uCultivoEsputo "uCultivoEsputo"
#define LANG_FT_tMicrobiologia_uCultivoEsputo "Tabla de Cultivo Esputo"
#define LANG_FL_tMicrobiologia_uModDate "uModDate"
#define LANG_FT_tMicrobiologia_uModDate "Unix timestamp for last update"
#define LANG_FL_tMicrobiologia_uUrocultivo "uUrocultivo"
#define LANG_FT_tMicrobiologia_uUrocultivo "Tabla de Urocultivo"
#define LANG_FL_tMicrobiologia_uOwner "uOwner"
#define LANG_FT_tMicrobiologia_uOwner "Record owner"
#define LANG_FL_tMicrobiologia_uCultivoPB "uCultivoPB"
#define LANG_FT_tMicrobiologia_uCultivoPB "Tabla de Cultivo PB"
#define LANG_FL_tMicrobiologia_uModBy "uModBy"
#define LANG_FT_tMicrobiologia_uModBy "Record modifed by"
#define LANG_FL_tMicrobiologia_uHemocultivo "uHemocultivo"
#define LANG_FT_tMicrobiologia_uHemocultivo "Tabla de Hemocultivo"
#define LANG_FL_tMicrobiologia_cLabel "cLabel"
#define LANG_FT_tMicrobiologia_cLabel "Short label"
#define LANG_FL_tMicrobiologia_uCultivoHueso "uCultivoHueso"
#define LANG_FT_tMicrobiologia_uCultivoHueso "Tabla de Cultivo Hueso"
#define LANG_FL_tMicrobiologia_uCreatedDate "uCreatedDate"
#define LANG_FT_tMicrobiologia_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tMicrobiologia_uCultivoLCR "uCultivoLCR"
#define LANG_FT_tMicrobiologia_uCultivoLCR "Tabla de Cultivo LCR"
#define LANG_FL_tMicrobiologia_uMicrobiologia "uMicrobiologia"
#define LANG_FT_tMicrobiologia_uMicrobiologia "Primary key"
#define LANG_FL_tMicrobiologia_uCultivoCateter "uCultivoCateter"
#define LANG_FT_tMicrobiologia_uCultivoCateter "Tabla de Cultivo Cateter"
#define LANG_FL_tHemocultivo_cLabel "cLabel"
#define LANG_FT_tHemocultivo_cLabel "Short label"
#define LANG_FL_tHemocultivo_cBacteria "cBacteria"
#define LANG_FT_tHemocultivo_cBacteria "Nombre de la bacteria"
#define LANG_FL_tHemocultivo_uCreatedDate "uCreatedDate"
#define LANG_FT_tHemocultivo_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tHemocultivo_uHemocultivo "uHemocultivo"
#define LANG_FT_tHemocultivo_uHemocultivo "Primary key"
#define LANG_FL_tHemocultivo_uCreatedBy "uCreatedBy"
#define LANG_FT_tHemocultivo_uCreatedBy "Record created by"
#define LANG_FL_tHemocultivo_cResistencia "cResistencia"
#define LANG_FT_tHemocultivo_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tHemocultivo_uModDate "uModDate"
#define LANG_FT_tHemocultivo_uModDate "Unix timestamp for last update"
#define LANG_FL_tHemocultivo_uOwner "uOwner"
#define LANG_FT_tHemocultivo_uOwner "Record owner"
#define LANG_FL_tHemocultivo_cSensibilidad "cSensibilidad"
#define LANG_FT_tHemocultivo_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tHemocultivo_uModBy "uModBy"
#define LANG_FT_tHemocultivo_uModBy "Record modifed by"
#define LANG_FL_tUrocultivo_uCreatedDate "uCreatedDate"
#define LANG_FT_tUrocultivo_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tUrocultivo_cBacteria "cBacteria"
#define LANG_FT_tUrocultivo_cBacteria "Nombre de la bacteria"
#define LANG_FL_tUrocultivo_uUrocultivo "uUrocultivo"
#define LANG_FT_tUrocultivo_uUrocultivo "Primary key"
#define LANG_FL_tUrocultivo_uCreatedBy "uCreatedBy"
#define LANG_FT_tUrocultivo_uCreatedBy "Record created by"
#define LANG_FL_tUrocultivo_uModDate "uModDate"
#define LANG_FT_tUrocultivo_uModDate "Unix timestamp for last update"
#define LANG_FL_tUrocultivo_cResistencia "cResistencia"
#define LANG_FT_tUrocultivo_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tUrocultivo_uOwner "uOwner"
#define LANG_FT_tUrocultivo_uOwner "Record owner"
#define LANG_FL_tUrocultivo_uModBy "uModBy"
#define LANG_FT_tUrocultivo_uModBy "Record modifed by"
#define LANG_FL_tUrocultivo_cSensibilidad "cSensibilidad"
#define LANG_FT_tUrocultivo_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tUrocultivo_cLabel "cLabel"
#define LANG_FT_tUrocultivo_cLabel "Short label"
#define LANG_FL_tCultivoCateter_uCultivoCateter "uCultivoCateter"
#define LANG_FT_tCultivoCateter_uCultivoCateter "Primary key"
#define LANG_FL_tCultivoCateter_uCreatedBy "uCreatedBy"
#define LANG_FT_tCultivoCateter_uCreatedBy "Record created by"
#define LANG_FL_tCultivoCateter_uModDate "uModDate"
#define LANG_FT_tCultivoCateter_uModDate "Unix timestamp for last update"
#define LANG_FL_tCultivoCateter_cBacteria "cBacteria"
#define LANG_FT_tCultivoCateter_cBacteria "Nombre de la bacteria"
#define LANG_FL_tCultivoCateter_uOwner "uOwner"
#define LANG_FT_tCultivoCateter_uOwner "Record owner"
#define LANG_FL_tCultivoCateter_uModBy "uModBy"
#define LANG_FT_tCultivoCateter_uModBy "Record modifed by"
#define LANG_FL_tCultivoCateter_cResistencia "cResistencia"
#define LANG_FT_tCultivoCateter_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tCultivoCateter_cLabel "cLabel"
#define LANG_FT_tCultivoCateter_cLabel "Short label"
#define LANG_FL_tCultivoCateter_uCreatedDate "uCreatedDate"
#define LANG_FT_tCultivoCateter_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tCultivoCateter_cSensibilidad "cSensibilidad"
#define LANG_FT_tCultivoCateter_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tCultivoHueso_uModDate "uModDate"
#define LANG_FT_tCultivoHueso_uModDate "Unix timestamp for last update"
#define LANG_FL_tCultivoHueso_cSensibilidad "cSensibilidad"
#define LANG_FT_tCultivoHueso_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tCultivoPB_uOwner "uOwner"
#define LANG_FT_tCultivoPB_uOwner "Record owner"
#define LANG_FL_tCultivoPB_cSensibilidad "cSensibilidad"
#define LANG_FT_tCultivoPB_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tCultivoPB_uModBy "uModBy"
#define LANG_FT_tCultivoPB_uModBy "Record modifed by"
#define LANG_FL_tCultivoHueso_uOwner "uOwner"
#define LANG_FT_tCultivoHueso_uOwner "Record owner"
#define LANG_FL_tCultivoHueso_uModBy "uModBy"
#define LANG_FT_tCultivoHueso_uModBy "Record modifed by"
#define LANG_FL_tCultivoHueso_cBacteria "cBacteria"
#define LANG_FT_tCultivoHueso_cBacteria "Nombre de la bacteria"
#define LANG_FL_tCultivoPB_cLabel "cLabel"
#define LANG_FT_tCultivoPB_cLabel "Short label"
#define LANG_FL_tCultivoPB_cBacteria "cBacteria"
#define LANG_FT_tCultivoPB_cBacteria "Nombre de la bacteria"
#define LANG_FL_tCultivoPB_uCreatedDate "uCreatedDate"
#define LANG_FT_tCultivoPB_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tCultivoHueso_cLabel "cLabel"
#define LANG_FT_tCultivoHueso_cLabel "Short label"
#define LANG_FL_tCultivoHueso_uCreatedDate "uCreatedDate"
#define LANG_FT_tCultivoHueso_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tCultivoPB_uCultivoPB "uCultivoPB"
#define LANG_FT_tCultivoPB_uCultivoPB "Primary key"
#define LANG_FL_tCultivoHueso_cResistencia "cResistencia"
#define LANG_FT_tCultivoHueso_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tCultivoPB_uCreatedBy "uCreatedBy"
#define LANG_FT_tCultivoPB_uCreatedBy "Record created by"
#define LANG_FL_tCultivoPB_cResistencia "cResistencia"
#define LANG_FT_tCultivoPB_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tCultivoPB_uModDate "uModDate"
#define LANG_FT_tCultivoPB_uModDate "Unix timestamp for last update"
#define LANG_FL_tCultivoHueso_uCultivoHueso "uCultivoHueso"
#define LANG_FT_tCultivoHueso_uCultivoHueso "Primary key"
#define LANG_FL_tCultivoHueso_uCreatedBy "uCreatedBy"
#define LANG_FT_tCultivoHueso_uCreatedBy "Record created by"
#define LANG_FL_tCultivoEsputo_cSensibilidad "cSensibilidad"
#define LANG_FT_tCultivoEsputo_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tCultivoEsputo_cLabel "cLabel"
#define LANG_FT_tCultivoEsputo_cLabel "Short label"
#define LANG_FL_tCultivoEsputo_uCreatedDate "uCreatedDate"
#define LANG_FT_tCultivoEsputo_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tCultivoEsputo_cBacteria "cBacteria"
#define LANG_FT_tCultivoEsputo_cBacteria "Nombre de la bacteria"
#define LANG_FL_tCultivoEsputo_uCultivoEsputo "uCultivoEsputo"
#define LANG_FT_tCultivoEsputo_uCultivoEsputo "Primary key"
#define LANG_FL_tCultivoEsputo_uCreatedBy "uCreatedBy"
#define LANG_FT_tCultivoEsputo_uCreatedBy "Record created by"
#define LANG_FL_tCultivoEsputo_uModDate "uModDate"
#define LANG_FT_tCultivoEsputo_uModDate "Unix timestamp for last update"
#define LANG_FL_tCultivoEsputo_cResistencia "cResistencia"
#define LANG_FT_tCultivoEsputo_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tCultivoEsputo_uOwner "uOwner"
#define LANG_FT_tCultivoEsputo_uOwner "Record owner"
#define LANG_FL_tCultivoEsputo_uModBy "uModBy"
#define LANG_FT_tCultivoEsputo_uModBy "Record modifed by"
#define LANG_FL_tCultivoLCR_cLabel "cLabel"
#define LANG_FT_tCultivoLCR_cLabel "Short label"
#define LANG_FL_tCultivoLCR_uCreatedDate "uCreatedDate"
#define LANG_FT_tCultivoLCR_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tCultivoLCR_cSensibilidad "cSensibilidad"
#define LANG_FT_tCultivoLCR_cSensibilidad "Lista de abreviaturas de antibioticos"
#define LANG_FL_tCultivoLCR_uCultivoLCR "uCultivoLCR"
#define LANG_FT_tCultivoLCR_uCultivoLCR "Primary key"
#define LANG_FL_tCultivoLCR_uCreatedBy "uCreatedBy"
#define LANG_FT_tCultivoLCR_uCreatedBy "Record created by"
#define LANG_FL_tCultivoLCR_uModDate "uModDate"
#define LANG_FT_tCultivoLCR_uModDate "Unix timestamp for last update"
#define LANG_FL_tCultivoLCR_cBacteria "cBacteria"
#define LANG_FT_tCultivoLCR_cBacteria "Nombre de la bacteria"
#define LANG_FL_tCultivoLCR_uOwner "uOwner"
#define LANG_FT_tCultivoLCR_uOwner "Record owner"
#define LANG_FL_tCultivoLCR_uModBy "uModBy"
#define LANG_FT_tCultivoLCR_uModBy "Record modifed by"
#define LANG_FL_tCultivoLCR_cResistencia "cResistencia"
#define LANG_FT_tCultivoLCR_cResistencia "Lista de abreviaturas de resistencias"
#define LANG_FL_tOrina_uCreatedDate "uCreatedDate"
#define LANG_FT_tOrina_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tOrina_cLabel "cLabel"
#define LANG_FT_tOrina_cLabel "Short label"
#define LANG_FL_tOrina_uModBy "uModBy"
#define LANG_FT_tOrina_uModBy "Record modifed by"
#define LANG_FL_tOrina_uLeucocitos "uLeucocitos"
#define LANG_FT_tOrina_uLeucocitos "leucocitos en orina +"
#define LANG_FL_tOrina_uGermenes "uGermenes"
#define LANG_FT_tOrina_uGermenes "Germenes en orina +"
#define LANG_FL_tOrina_uOwner "uOwner"
#define LANG_FT_tOrina_uOwner "Record owner"
#define LANG_FL_tOrina_uPiocitos "uPiocitos"
#define LANG_FT_tOrina_uPiocitos "Piocitos en orina +"
#define LANG_FL_tOrina_uCelulasEpiteliales "uCelulasEpiteliales"
#define LANG_FT_tOrina_uCelulasEpiteliales "Celulas epitliales en orina +"
#define LANG_FL_tOrina_uCreatedBy "uCreatedBy"
#define LANG_FT_tOrina_uCreatedBy "Record created by"
#define LANG_FL_tOrina_uOrina "uOrina"
#define LANG_FT_tOrina_uOrina "Primary key"
#define LANG_FL_tOrina_uModDate "uModDate"
#define LANG_FT_tOrina_uModDate "Unix timestamp for last update"
#define LANG_FL_tOrina_uHematies "uHematies"
#define LANG_FT_tOrina_uHematies "Hematies en orina +"
#define LANG_FL_tVirologia_cLabel "cLabel"
#define LANG_FT_tVirologia_cLabel "Short label"
#define LANG_FL_tVirologia_uCreatedDate "uCreatedDate"
#define LANG_FT_tVirologia_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tVirologia_uHIV "uHIV"
#define LANG_FT_tVirologia_uHIV "Carga viral HIV"
#define LANG_FL_tVirologia_uVirologia "uVirologia"
#define LANG_FT_tVirologia_uVirologia "Primary key"
#define LANG_FL_tVirologia_uCreatedBy "uCreatedBy"
#define LANG_FT_tVirologia_uCreatedBy "Record created by"
#define LANG_FL_tVirologia_uModDate "uModDate"
#define LANG_FT_tVirologia_uModDate "Unix timestamp for last update"
#define LANG_FL_tVirologia_uHVC "uHVC"
#define LANG_FT_tVirologia_uHVC "Carga viral Hepatitis C"
#define LANG_FL_tVirologia_uOwner "uOwner"
#define LANG_FT_tVirologia_uOwner "Record owner"
#define LANG_FL_tVirologia_uModBy "uModBy"
#define LANG_FT_tVirologia_uModBy "Record modifed by"
#define LANG_FL_tVirologia_uHVB "uHVB"
#define LANG_FT_tVirologia_uHVB "Carga viral Hepatitis B"
#define LANG_FL_tVitales_uCreatedBy "uCreatedBy"
#define LANG_FT_tVitales_uCreatedBy "Record created by"
#define LANG_FL_tVitales_uModDate "uModDate"
#define LANG_FT_tVitales_uModDate "Unix timestamp for last update"
#define LANG_FL_tVitales_uTAD "uTAD"
#define LANG_FT_tVitales_uTAD "Tension arterial diastolica mmHg"
#define LANG_FL_tVitales_uFR "uFR"
#define LANG_FT_tVitales_uFR "Frecuencia respiratoria en respiraciones por minuto"
#define LANG_FL_tVitales_uOwner "uOwner"
#define LANG_FT_tVitales_uOwner "Record owner"
#define LANG_FL_tVitales_uModBy "uModBy"
#define LANG_FT_tVitales_uModBy "Record modifed by"
#define LANG_FL_tVitales_uTAS "uTAS"
#define LANG_FT_tVitales_uTAS "Tension arterial sistolica mmHg"
#define LANG_FL_tVitales_uFC "uFC"
#define LANG_FT_tVitales_uFC "Frecuencia cardiaca en latidos por minuto"
#define LANG_FL_tVitales_cLabel "cLabel"
#define LANG_FT_tVitales_cLabel "Short label"
#define LANG_FL_tVitales_uCreatedDate "uCreatedDate"
#define LANG_FT_tVitales_uCreatedDate "Unix timestamp for creation date"
#define LANG_FL_tVitales_uTemp "uTemp"
#define LANG_FT_tVitales_uTemp "Temperatura grados C"
#define LANG_FL_tVitales_uSatO2 "uSatO2"
#define LANG_FT_tVitales_uSatO2 "Porcentaje saturacion de oxigeno %"
#define LANG_FL_tVitales_uPaciente "uPaciente"
#define LANG_FT_tVitales_uPaciente "Numero de paciente"
#define LANG_FL_tVitales_uVitales "uVitales"
#define LANG_FT_tVitales_uVitales "Primary key"


//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_uServer "uServer"
#define LANG_FT_tConfiguration_uServer "uServer"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Encrypted cgi login password"
#define LANG_FL_tAuthorize_cClrPasswd "cClrPasswd"
#define LANG_FT_tAuthorize_cClrPasswd "Optionally used non encrypted login password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Name of Archive Table Ex. tNov2009"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Primary Key"
#define LANG_FL_tJob_cLabel "cLabel"
#define LANG_FT_tJob_cLabel "Label for user feedback"
#define LANG_FL_tJob_cJobName "cJobName"
#define LANG_FT_tJob_cJobName "Subsystem.Function style job name"
#define LANG_FL_tJob_uServer "uServer"
#define LANG_FT_tJob_uServer "The server the job should run on"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Remote subsystem server function arguments"
#define LANG_FL_tJob_uJobDate "uJobDate"
#define LANG_FT_tJob_uJobDate "Unix seconds for job to start to be considered"
#define LANG_FL_tJob_uJobStatus "uJobStatus"
#define LANG_FT_tJob_uJobStatus "Waiting, being processed, done, error"
#define LANG_FL_tJob_cRemoteMsg "cRemoteMsg"
#define LANG_FT_tJob_cRemoteMsg "Remote subsytem error message"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tProject
#define LANG_FL_tProject_uProject "uProject"
#define LANG_FT_tProject_uProject "Primary Key"
#define LANG_FL_tProject_cLabel "cLabel"
#define LANG_FT_tProject_cLabel "Short label"
#define LANG_FL_tProject_uProjectStatus "uProjectStatus"
#define LANG_FT_tProject_uProjectStatus "Status of project"
#define LANG_FL_tProject_uTemplateSet "uTemplateSet"
#define LANG_FT_tProject_uTemplateSet "Template set or group to use"
#define LANG_FL_tProject_cDescription "cDescription"
#define LANG_FT_tProject_cDescription "Project blurb"
#define LANG_FL_tProject_cDirectory "cDirectory"
#define LANG_FT_tProject_cDirectory "Project blurb"
#define LANG_FL_tProject_uOwner "uOwner"
#define LANG_FT_tProject_uOwner "Record owner"
#define LANG_FL_tProject_uCreatedBy "uCreatedBy"
#define LANG_FT_tProject_uCreatedBy "uClient for last insert"
#define LANG_FL_tProject_uCreatedDate "uCreatedDate"
#define LANG_FT_tProject_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tProject_uModBy "uModBy"
#define LANG_FT_tProject_uModBy "uClient for last update"
#define LANG_FL_tProject_uModDate "uModDate"
#define LANG_FT_tProject_uModDate "Unix seconds date last update"
//tTable
#define LANG_FL_tTable_uTable "uTable"
#define LANG_FT_tTable_uTable "Primary Key"
#define LANG_FL_tTable_cLabel "cLabel"
#define LANG_FT_tTable_cLabel "Short label"
#define LANG_FL_tTable_uProject "uProject"
#define LANG_FT_tTable_uProject "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uTableOrder "uTableOrder"
#define LANG_FT_tTable_uTableOrder "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uSourceLock "uSourceLock"
#define LANG_FT_tTable_uSourceLock "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_cDescription "cDescription"
#define LANG_FT_tTable_cDescription "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_cLegend "cLegend"
#define LANG_FT_tTable_cLegend "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_cToolTip "cToolTip"
#define LANG_FT_tTable_cToolTip "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uNewLevel "uNewLevel"
#define LANG_FT_tTable_uNewLevel "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uModLevel "uModLevel"
#define LANG_FT_tTable_uModLevel "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uDelLevel "uDelLevel"
#define LANG_FT_tTable_uDelLevel "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uReadLevel "uReadLevel"
#define LANG_FT_tTable_uReadLevel "New Table Creation Minimum uPermLevel"
#define LANG_FL_tTable_uOwner "uOwner"
#define LANG_FT_tTable_uOwner "Record owner"
#define LANG_FL_tTable_uCreatedBy "uCreatedBy"
#define LANG_FT_tTable_uCreatedBy "uClient for last insert"
#define LANG_FL_tTable_uCreatedDate "uCreatedDate"
#define LANG_FT_tTable_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTable_uModBy "uModBy"
#define LANG_FT_tTable_uModBy "uClient for last update"
#define LANG_FL_tTable_uModDate "uModDate"
#define LANG_FT_tTable_uModDate "Unix seconds date last update"
//tField
#define LANG_FL_tField_uField "uField"
#define LANG_FT_tField_uField "Primary Key"
#define LANG_FL_tField_cLabel "cLabel"
#define LANG_FT_tField_cLabel "Short label"
#define LANG_FL_tField_uProject "uProject"
#define LANG_FT_tField_uProject "Field Belongs to this Table"
#define LANG_FL_tField_uTable "uTable"
#define LANG_FT_tField_uTable "Field Belongs to this Table"
#define LANG_FL_tField_uOrder "uOrder"
#define LANG_FT_tField_uOrder "Order in Form"
#define LANG_FL_tField_uFieldType "uFieldType"
#define LANG_FT_tField_uFieldType "Field Belongs to this Table"
#define LANG_FL_tField_uIndexType "uIndexType"
#define LANG_FT_tField_uIndexType "SQL Index If Any"
#define LANG_FL_tField_cFKSpec "cFKSpec"
#define LANG_FT_tField_cFKSpec "Foreign Key Table and Field"
#define LANG_FL_tField_cExtIndex "cExtIndex"
#define LANG_FT_tField_cExtIndex "Optional Multiple Index SQL Create Code"
#define LANG_FL_tField_cTitle "cTitle"
#define LANG_FT_tField_cTitle "Tool Tip Text"
#define LANG_FL_tField_uSQLSize "uSQLSize"
#define LANG_FT_tField_uSQLSize "SQL Data Storage Size if Applies"
#define LANG_FL_tField_uHtmlXSize "uHtmlXSize"
#define LANG_FT_tField_uHtmlXSize "HTML X/Width Size if Applies"
#define LANG_FL_tField_uHtmlYSize "uHtmlYSize"
#define LANG_FT_tField_uHtmlYSize "HTML Y/Height Size if Applies"
#define LANG_FL_tField_uHtmlMax "uHtmlMax"
#define LANG_FT_tField_uHtmlMax "HTML Max/Length if Applies"
#define LANG_FL_tField_cFormDefault "cFormDefault"
#define LANG_FT_tField_cFormDefault "HTML Form Default Value if Applies"
#define LANG_FL_tField_cSQLDefault "cSQLDefault"
#define LANG_FT_tField_cSQLDefault "SQL Default Value if Applies"
#define LANG_FL_tField_uReadLevel "uReadLevel"
#define LANG_FT_tField_uReadLevel "Row Read/Display Level"
#define LANG_FL_tField_uModLevel "uModLevel"
#define LANG_FT_tField_uModLevel "Row Mod Level"
#define LANG_FL_tField_uOwner "uOwner"
#define LANG_FT_tField_uOwner "Record owner"
#define LANG_FL_tField_uCreatedBy "uCreatedBy"
#define LANG_FT_tField_uCreatedBy "uClient for last insert"
#define LANG_FL_tField_uCreatedDate "uCreatedDate"
#define LANG_FT_tField_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tField_uModBy "uModBy"
#define LANG_FT_tField_uModBy "uClient for last update"
#define LANG_FL_tField_uModDate "uModDate"
#define LANG_FT_tField_uModDate "Unix seconds date last update"
//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tProjectStatus
#define LANG_FL_tProjectStatus_uStatus "uStatus"
#define LANG_FT_tProjectStatus_uStatus "Primary Key"
#define LANG_FL_tProjectStatus_cLabel "cLabel"
#define LANG_FT_tProjectStatus_cLabel "Short label"
#define LANG_FL_tProjectStatus_uLockMain "uLockMain"
#define LANG_FT_tProjectStatus_uLockMain "Do not replace main.c on build"
#define LANG_FL_tProjectStatus_uLockMainFunc "uLockMainFunc"
#define LANG_FT_tProjectStatus_uLockMainFunc "Do not replace mainfunc.h on build"
#define LANG_FL_tProjectStatus_uLockModule "uLockModule"
#define LANG_FT_tProjectStatus_uLockModule "Do not replace table .c file on build"
#define LANG_FL_tProjectStatus_uLockModuleFunc "uLockModuleFunc"
#define LANG_FT_tProjectStatus_uLockModuleFunc "Do not replace table func.h file on build"
#define LANG_FL_tProjectStatus_uLockMakefile "uLockMakefile"
#define LANG_FT_tProjectStatus_uLockMakefile "Do not replace makefile on build"
#define LANG_FL_tProjectStatus_uLockInclude "uLockInclude"
#define LANG_FT_tProjectStatus_uLockInclude "Do not replace mysqlrad.h on build"
#define LANG_FL_tProjectStatus_uLockLanguage "uLockLanguage"
#define LANG_FT_tProjectStatus_uLockLanguage "Do not replace languagex.h files on build"
#define LANG_FL_tProjectStatus_uLockCapFiles "uLockCapFiles"
#define LANG_FT_tProjectStatus_uLockCapFiles "Do not replace INSTALL and similar files on build"
#define LANG_FL_tProjectStatus_uOwner "uOwner"
#define LANG_FT_tProjectStatus_uOwner "Record owner"
#define LANG_FL_tProjectStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tProjectStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tProjectStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tProjectStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tProjectStatus_uModBy "uModBy"
#define LANG_FT_tProjectStatus_uModBy "uClient for last update"
#define LANG_FL_tProjectStatus_uModDate "uModDate"
#define LANG_FT_tProjectStatus_uModDate "Unix seconds date last update"
//tFieldType
#define LANG_FL_tFieldType_uFieldType "uFieldType"
#define LANG_FT_tFieldType_uFieldType "Primary Key"
#define LANG_FL_tFieldType_cLabel "cLabel"
#define LANG_FT_tFieldType_cLabel "Short label"
#define LANG_FL_tFieldType_uRADType "uRADType"
#define LANG_FT_tFieldType_uRADType "Internal Define Number"
#define LANG_FL_tFieldType_cSQLCreatePart "cSQLCreatePart"
#define LANG_FT_tFieldType_cSQLCreatePart "Internal Define Number"
#define LANG_FL_tFieldType_uOwner "uOwner"
#define LANG_FT_tFieldType_uOwner "Record owner"
#define LANG_FL_tFieldType_uCreatedBy "uCreatedBy"
#define LANG_FT_tFieldType_uCreatedBy "uClient for last insert"
#define LANG_FL_tFieldType_uCreatedDate "uCreatedDate"
#define LANG_FT_tFieldType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tFieldType_uModBy "uModBy"
#define LANG_FT_tFieldType_uModBy "uClient for last update"
#define LANG_FL_tFieldType_uModDate "uModDate"
#define LANG_FT_tFieldType_uModDate "Unix seconds date last update"
//tIndexType
#define LANG_FL_tIndexType_uIndexType "uIndexType"
#define LANG_FT_tIndexType_uIndexType "Primary Key"
#define LANG_FL_tIndexType_cLabel "cLabel"
#define LANG_FT_tIndexType_cLabel "Short label"
#define LANG_FL_tIndexType_uOwner "uOwner"
#define LANG_FT_tIndexType_uOwner "Record owner"
#define LANG_FL_tIndexType_uCreatedBy "uCreatedBy"
#define LANG_FT_tIndexType_uCreatedBy "uClient for last insert"
#define LANG_FL_tIndexType_uCreatedDate "uCreatedDate"
#define LANG_FT_tIndexType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tIndexType_uModBy "uModBy"
#define LANG_FT_tIndexType_uModBy "uClient for last update"
#define LANG_FL_tIndexType_uModDate "uModDate"
#define LANG_FT_tIndexType_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Primary Key"
#define LANG_FL_tJob_cLabel "cLabel"
#define LANG_FT_tJob_cLabel "Label for user feedback"
#define LANG_FL_tJob_cServer "cServer"
#define LANG_FT_tJob_cServer "Server name ip or any server"
#define LANG_FL_tJob_cJobName "cJobName"
#define LANG_FT_tJob_cJobName "Subsystem.Function style job name"
#define LANG_FL_tJob_uJobSite "uJobSite"
#define LANG_FT_tJob_uJobSite "Owner of resources created/mod"
#define LANG_FL_tJob_uJobSiteUser "uJobSiteUser"
#define LANG_FT_tJob_uJobSiteUser "Site User ID"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Remote subsystem server function arguments"
#define LANG_FL_tJob_uJobDate "uJobDate"
#define LANG_FT_tJob_uJobDate "Unix seconds for job to start to be considered"
#define LANG_FL_tJob_uJobStatus "uJobStatus"
#define LANG_FT_tJob_uJobStatus "Waiting, being processed, done, error"
#define LANG_FL_tJob_cRemoteMsg "cRemoteMsg"
#define LANG_FT_tJob_cRemoteMsg "Remote subsytem error message"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
